use quadro;

INSERT INTO muebles (nombre,descripcion,tipo_mueble_id,imagen_path,plano_path,materiales_path,alto,ancho,profundidad,materiales,precio)
VALUES ('Cubic','Mesa baja conformada por dos vol&uacutemenes puros que conforman un atractivo conjunto. Realizada en melamina sobre MDF con dos cajones laterales.',1,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','27','80','80','Melamina negra sobre MDF.','3500'),
('Line','La simplicidad y el car&aacutecter hacen que Line se adapte a cualquier disposici&oacuten y espacio. Realizada en madera maciza con tratamiento de laca blanca satinada.',1,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','40','50','80','Madera maciza con terminacion de laca satinada.','3200'),
('Compact','Compact se caracteriza por la armon&iacutea de sus materiales y el equilibrio de sus vol&uacutemenes. Realizada en una combinaci&oacuten de melaminas sobre MDF. ',1,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','40','52','92','Melamina blanca (sobre MDF) en apoyos y Roble Dakar o Ebano negro en estantes.','3000'),
('Cave','Cave nos ofrece una soluci&oacuten perfecta para nuestro living combinando vol&uacutemenes puros con la liviandad del vidrio. ',1,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','40','50','90','Melamina blanca y negra (sobre MDF) y estante de vidrio.','3400'),
('Square','Caracterizada por sus lineas puras y su arm&oacutenica combinaci&oacuten de materiales Square se adapta a las necesidades de cualquier espacio. ',1,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','30','50','85','Melamina negra (sobre MDF) y roble dakar, ebano negro o haya (sobre MDF).','2900'),
('Density','Density es una mesa que se destaca por su sencillez formal y estructural. Realizada en distintas opciones de melamina sobre MDF permitiendo asi su adaptaci&oacuten a distintos espacios.',2,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','80','90','160','Melamina Roble Dakar, Roble español o Ebano negro sobre MDF.','4400'),
('Obscure','Obscure es una mesa que se destaca por el contraste arm&oacutenico generado por sus apoyos de madera maciza y su tapa de melamina negra.',2,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','80','90','150','Apoyos en madera maciza Guatambu y tapa de melamina negra sobre MDF.','5900'),
('Point','Con formas puras y simples, Point se adapta de manera armoniosa a cualquier tipo de ambiente y disposici&oacuten.',2,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','83','130','130','Melamina Roble Dakar o Ebano negro sobre MDF y base de apoyo en melamina negra.','3800'),
('Plate','Por su forma y composici&oacuten Plate permite organizar y guardar objetos de manera sencilla. Realizado en melamina sobre MDF con un caj&oacuten y dos estantes.',3,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','55','55','40','Melamina blanca o negra sobre MDF.','1500'),
('Quadrate','La perfecta combinaci&oacuten de planos y vol&uacutemenes conforman Quadrate, una mesa de luz que se destaca por su est&eacutetica y funcionalidad. ',3,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','55','45','35','Melamina Roble Dakar, Ebano negro o Haya sobre MDF.','1400'),
('Cavity','Mueble de TV que sorprende por su simplicidad. Su composici&oacuten morfol&oacutegica convierte a Cavity en un mueble elegante. Posee un amplio caj&oacuten de guardado.',4,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','40','160','40','Melamina blanca sobre MDF.','4100'),
('Linear','Su principal caracter&iacutestica es la simplicidad en sus lineas y el equilibrio en su composici&oacuten. Posee dos cajones de guardado.',4,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','30','200','45','Melamina negra y blanca sobre MDF.','3800'),
('Scale','Con lineas rectas y una definida geometr&iacutea Scale se apodera del espacio y lo potencia. Posee dos amplios cajones.',4,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','40','230','50','Melamina blanca sobre MDF.','5000'),
('Box','Por su pureza y equilibrio, Box se adapta de manera armoniosa a cualquier espacio. Posee dos amplios cajones.',4,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','35','150','40','Melamina negra y blanca sobre MDF.','3700'),
('Cosmos','Cosmos ofrece una nueva propuesta por su aspecto moderno y funcional. Posee dos amplios cajones.',4,'Imagen.JPEG','Plano.JPEG','Materiales.JPEG','42','200','40','Melamina negra sobre MDF.','4700');
